services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongos1:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos1:27017,mongos2:27016,mongos3:27015/"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - app-network

  configSrv:
    image: mongo:latest
    container_name: configSrv
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data1:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27020" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s

  configSrv2:
    image: mongo:latest
    container_name: configSrv2
    restart: always
    ports:
      - "27021:27021"
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    volumes:
      - config-data2:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27021" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27021", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s

  configSrv3:
    image: mongo:latest
    container_name: configSrv3
    restart: always
    ports:
      - "27022:27022"
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    volumes:
      - config-data3:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27022" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27022", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s

  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.20
    volumes:
      - shard1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy

  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.30
    volumes:
      - shard2-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27019" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy

  mongos1:
    image: mongo:latest
    container_name: mongos1
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command: [ "mongos", "--configdb", "config_server/configSrv:27020,configSrv2:27021,configSrv3:27022", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1:
        condition: service_healthy
      shard2:
        condition: service_healthy

  mongos2:
    image: mongo:latest
    container_name: mongos2
    restart: always
    ports:
      - "27016:27016"
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    command: [ "mongos", "--configdb", "config_server/configSrv:27020,configSrv2:27021,configSrv3:27022", "--bind_ip_all", "--port", "27016" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27016", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1:
        condition: service_healthy
      shard2:
        condition: service_healthy

  mongos3:
    image: mongo:latest
    container_name: mongos3
    restart: always
    ports:
      - "27015:27015"
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    command: [ "mongos", "--configdb", "config_server/configSrv:27020,configSrv2:27021,configSrv3:27022", "--bind_ip_all", "--port", "27015" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27015", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1:
        condition: service_healthy
      shard2:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.17.0.0/24

volumes:
  config-data1:
  config-data2:
  config-data3:
  shard1-data:
  shard2-data: